### ISSUE TITLE
Server command terminal

### ISSUE THREAD

**Issue by Zhythero** [zekroTJA/spigot-autobuild#1]
Hi thanks for the image.

It would be awesome if we can run server commands like /info or /give to the server via its terminal without going inside the container.

Example: `docker exec <container_name> server_command /info`

**Comment by zekroTJA** [comment]
Hey, sorry for the late response, but for some reason, this project wa set to `Not watching`, so I wasn't notificated about the issue.

THis issue should be solved by commit fc807468bb84f2bf6cde0e05aea11fd7a6a3bc53.

I've added @itzg's [rcon-cli]() as RCON client into the image which can be simply accessed ad following:
```
# docker exec <container> rcon --port 25575 --password <rcon_pw> <server_command>
```

Please take a look at his [documentation on how to use the rcon-cli](https://github.com/itzg/rcon-cli#usage) if you need further information.
